server:
  port: 8083
  
spring:
  application:
    name:  car-trawler
  profiles:
    active: 'local'
  
#ENDPOINTS:
management:
  endpoints:
    web:
      exposure:
        include:
        - 'health'
        - 'info'